baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Viktor Martinek'
theme = 'beautifulhugo'

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
#googleAnalytics = "XXX"

[[menu.main]]
    name = "About"
    url = ""
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 2

[[menu.main]]
    name = "Talks"
    url = "talks/"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "publications/"
    weight = 4

[[menu.main]]
    name = "CV"
    url = "cv/"
    weight = 5

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = ""
  mainSections = ["post","posts"]
  logo = "prof_pic.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Viktor Martinek"
  email = "v.martinek@mail.de"
  github = "viktmar"
  gitlab = "v_mar"
  # twitter = "username"
  # linkedin = "username"
  # xing = "username"
  # youtube = "user/username" # or channel/channelname
  # paypal = "username"
